config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index' 
  
  # sessions
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  # login logout session
  resources :sessions, only: [:create] 
  # user
  resources :users
  # recipes
  resources :recipes

  # youtube video
  resources :videos, only: [:index, :new, :create, :destroy]
  
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user
	# recipe has 1 image
	mount_uploader :image, RecipeImageUploader

	validates_processing_of :image
	validate :image_size_validation
 	
 	# no image greater than 500KB gets uploaded
	private
	  def image_size_validation
	    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	  end


end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :authentications, dependent: :destroy
	has_many :recipes

	validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, presence: true
	validates :password_digest, length: { minimum: 5}
	validates :first_name,  presence: true
	


	# generates random token
	def User.new_token
	   SecureRandom.urlsafe_base64
	end
	

	# create_with_auth_hash will create a User object based on the information given by the provider
	 def self.create_with_auth_and_hash(authentication, auth_hash)
	   user = self.create!(
	   	 name: auth_hash["info"]["name"],
	     email: auth_hash["info"]["email"],
	     # 
	     password: SecureRandom.hex(10)
	   )
	   user.authentications << authentication
	   return user
	 end

	 # grab google to access google for user data
	 def google_token
	   x = self.authentications.find_by(provider: 'google_oauth2')
	   return x.token unless x.nil?
	 end
 
end

app/models/video.rb
class Video < ApplicationRecord
	
	link_format = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  	validates :link, presence: true, format:link_format

end

app/models/video_observer.rb
class VideoObserver < ActiveRecord::Observer
  # will run only before the record is saved
  def before_save(resource)
    video = Yt::Video.new url: resource.link
    resource.uid = video.id
    resource.title = video.title
    resource.likes = video.like_count
    resource.dislikes = video.dislike_count
    resource.published_at = video.published_at
  # will occur when the requested video was not found
  rescue Yt::Errors::NoItems
    resource.title = ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :require_valid_user!

  def current_user
  	# user logged or not
    if !session[:user_id].blank?
      @user ||= User.find(session[:user_id])
    end
  end

  def require_valid_user!
  	# user not logged 
    if current_user.nil?
      flash[:error] = 'You must be logged in to access that page!'
      redirect_to login_path
    end
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		# for pagination on recipe#index page
		# @recipe = Recipe.paginate(:page => params[:page], :per_page => 10)
		# @recipe = Recipe.starts_with(params[:starts_with]) if params[:starts_with].present?
		
		@q = Recipe.ransack(params[:q])
		@recipe = @q.result.paginate(:page => params[:page], :per_page => 10)

	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.user_id = current_user.id
		if @recipe.save
			flash[:success] = "recipe saved"
			redirect_to root_path
		else
			flash[:error] = "recipe not saved. Try again."
			render 'new'
		end
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
 		@recipe = Recipe.find(params[:id])

 		if @recipe.update(recipe_params)
 			flash[:success] = "You have successfully edited recipe!"
			redirect_to recipe_path(@recipe.id)
 		else
 			flash[:error] = "Recipe couldnt be edited. Try again."
 			redirect_to edit_recipe_path(@recipe.id)
 		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy

		redirect_to root_path
	end


	private

	def recipe_params
		params.require(:recipe).permit(
			:image,
			:remove_image,
			:name,
			:description,
			:ingredients,
			:instructions,
			:posted_at
			)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_valid_user!, except: [:destroy]

  # google omniauth
  def create_from_omniauth
  auth_hash = request.env["omniauth.auth"]
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
    if authentication.user
      user = authentication.user
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    # else: user logs in with OAuth for the first time
    else
      user = User.create_with_auth_and_hash(authentication, auth_hash)
      # you are expected to have a path that leads to a page for editing user details
      @next = root_path
      @notice = "User created. Please confirm or edit details"
    end

    session[:user_id] = user.id
    redirect_to @next, :notice => @notice
  end

  def new
  end

  def create
  	# resets user sessions
  	reset_session
    @user = User.find_by(email: session_params[:email])

    if @user && @user.authenticate(session_params[:password])
    # logs user in if user exist and allowed to authenticate
      session[:user_id] = @user.id
      flash[:success] = 'Welcome!'
      redirect_to root_path
    else
    # if email or password incorrect
      flash[:error] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def destroy
  	# for logging out, resets user session
  	reset_session
  end

  def session_params
    params.require(:session).permit(
      :name,
      :email,
      :password
      )
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_valid_user!
	before_action :reset_session

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			flash[:success] = "Account created. Sign in to continue."
			redirect_to login_path
		else
			flash[:error] = "User was not saved"
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(
			:first_name,
			:email,
			:password,
			:password_confirmation
			)
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  	 @videos = Video.order('created_at DESC')
  end

  def new
    @video = Video.new
  end

  def create
  	@video = Video.new(video_params)
  	if @video.save
    	flash[:success] = 'Video added!'
    	redirect_to videos_path
  	else
    	render 'new'
  	end

  end

  def destroy
  	@video = Video.find(params[:id])
  	@video.destroy

  	redirect_to videos_path
  end

  private

	def video_params
	  params.require(:video).permit(:link)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session. (remember me feature)
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        
        <!-- hamepage nav -->
        <div class="navbar-brand">
          <%= link_to 'LetsCook', root_path %>
        </div>
        
        <!-- session nav -->
        <div id="user_nav">
          <% if current_user %>
            <%= link_to "Log Out", logout_path %>
            <%= link_to "Videos", videos_path %>
            <%= link_to "New video", new_video_path %>
          <% else %>
            <%= link_to "Register", new_user_path %> |
            <%= link_to "Log In", login_path %>
          <% end %>
        </div>

        <!-- website nav -->
        
      
    </nav>

    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe_form.html.erb
<!-- partial for recipes form -->

<%= form_for @recipe, local: true do |f| %>

	<%= render 'shared/error_messages' %>

	<!-- field to upload image file -->
	<div class="form-group">
		<%= f.label :image  %>
		<%= f.file_field :image, class: 'form-control' , placeholder: 'Recipe image'  %>
		<!-- if there is already an image object -->
		<% if f.object.image? %>
			<!-- image displayed -->
	      <%= image_tag f.object.image.medium.url %>
	      	<!-- remove image option -->
	      <%= f.label :remove_image %>
	      <%= f.check_box :remove_image %> 
    	<% end %>
	</div>

	<div class = 'form-group'>
		<%= f.label :recipe_name %>
		<%= f.text_field :name, class: 'form-control' , placeholder: 'Recipe name'%>
	</div>

	<div class = 'form-group'>
		<%= f.label :description %>
		<%= f.text_field :description, class: 'form-control' , placeholder: 'Description' %>
	</div>

	<div class = 'form-group'>
		<%= f.label :ingredients %>
		<%= f.text_field :ingredients, class: 'form-control' , placeholder: 'Ingredients' %>
	</div>

	<div class = 'form-group'>
		<%= f.label :instructions %>
		<%= f.text_field :instructions, class: 'form-control' , placeholder: 'Instructions' %>
	</div>

	<%= f.submit class: 'btn btn-primary' %>

<% end %> 

app/views/recipes/edit.html.erb
<!-- edit recipe page -->

<div class= "container" >

	<%= link_to 'All recipes', root_path %>
	
	<h2>Edit Recipe</h2>
	
		<%= render 'shared/error_messages' %>
		<%= render '/recipes/recipe_form' %>
</div>

app/views/recipes/index.html.erb
<div class= "container-fluid">
	<h1>Homepage for recipes</h1>

	<!-- flashes welcome user notice -->
	<% if flash[:success] %>
	  <%= flash[:success] %>
	<% end %>
	<br>
	Logged as <strong><%= current_user.first_name %></strong>
</div>

<div class="container-fluid">
	<div class="jumbotron">
		<%= link_to 'New Recipe', new_recipe_path %>

		<!-- search form -->
		<%= search_form_for @q, local: true do |f| %>
			
			<%= f.label :Search %>
			<%= f.search_field :name_cont %>
			<%= f.submit  %>

		<% end %>
		
		<!-- pagination -->
		<div class="pagination">
			<%= will_paginate @recipe %>
		</div>
		<!-- contents -->
		<table>
			<tr>
				<th><%= sort_link(@q, :name) %></th>
				<th>Description</th>
				<th></th>
			</tr>

			<% @recipe.each do |recipe| %>
				<tr>
					<td><%= recipe.name %></td>
					<td><%= recipe.description %></td>
					<td><%= link_to '[View recipe]', recipe_path(recipe.id) %></td>
					<td><%= link_to '[Edit]', edit_recipe_path(recipe.id) %></td>
					<td><%= link_to '[Delete]', recipe_path(recipe.id), method: :delete, data: { confirm: 'Are you sure?'} %></td>
				</tr>
			<% end %>

		</table>
	</div>
</div>

app/views/recipes/new.html.erb
<!-- new recipes form -->

<div class = "container">

	<h2> Create a recipe </h2>
	
	<%= render 'shared/error_messages' %>
	<%= render '/recipes/recipe_form' %>

</div>

app/views/recipes/show.html.erb
<!-- recipe show page -->

<div class= "container-fluid">

	<%= link_to 'All recipes', root_path %>
	<%= link_to 'Edit recipes', edit_recipe_path(@recipe.id) %>
	
	<h2><%= @recipe.name %> Recipe </h2>
	
	<!-- recipe image -->
	<%= image_tag @recipe.image.medium.url.to_s %>
	<br>
	<strong>posted at</strong>
	
	<!-- recipe descriptions -->
	
		<p>Description:
			<%= @recipe.description %>
		</p>
		<p> Ingredients:
			<%= @recipe.ingredients %>
		</p>
		<p> Instructions:
			<%= @recipe.instructions %>
		</p>
	
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	 <div class='alert alert-danger'>
	   <p>Please correct the following errors:</p>
	   	<ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	    </ul>
	 </div>
<% end %>

app/views/users/new.html.erb
<!-- create new user -->
<div class="container text-center form-group">

	<h2>Sign up for an account</h2>
	<%= form_for @user do |f| %>

	<%= render 'shared/error_messages' %>

	  <div class='form-group'>
	    <%= f.label :first_name %>
	    <%= f.text_field :first_name, class: 'form-control' , placeholder: 'Username' %>
	  </div>

	  <div class='form-group'>
	    <%= f.label :email %>
	    <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
	  </div>

	  <div class='form-group'>
	    <%= f.label :password %>
	    <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
	  </div>

	   <div class='form-group'>
	    <%= f.label :password_confirmation, "Confirmation" %>
	    <%= f.password_field :password_confirmation, class: 'form-control' , placeholder: 'Confirm Password'%>
	  </div>

	  <%= f.submit 'Sign up', class: 'btn btn-primary' %>

	<% end %>

<p class='mt-2'>
  Already have an account? <%= link_to 'Click here to sign in.', login_path %>
  <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
</p>


</div>

app/views/videos/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Share your videos with the world!</h1>
    <p>Click the button below to share your video from YouTube.</p>
    <p>
      <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

<% if @videos.any? %>
  <div class="container">
  <h1>Latest videos</h1>
   <div id="player-wrapper"></div>
   <!-- divide the array of videos into groups of 3 elements -->
    <% @videos.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.each do |video| %>
          <% if video %>
            <div class="col-md-4">
              <div class="yt_video thumbnail">
                <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                                      class: 'img-rounded'),
                            "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
                             <div class="caption">
                  <h5><%= video.title %></h5>
                  <p>Published at <%= video.published_at.strftime('%-d %B %Y %H:%M:%S') %></p>
                  <p>
                    <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.likes %> likes
                    <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.dislikes %> dislikes
                  </p>
                  <td><%= link_to '[Delete]', video_path(video.id), method: :delete, data: { confirm: 'Are you sure?'} %></td>
                  </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/videos/new.html.erb
<div class="container">
  <h1>New video</h1>

  <%= form_for @video do |f| %>
	<%= render 'shared/error_messages' %>

	<div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  

  <% end %>




</div>